version: '3'

services:
  node-app:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:1127"
      
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - mysql
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_PASSWORD=123456789
      - MYSQL_DATABASE=company
  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456789
      MYSQL_DATABASE: company
      MYSQL_PASSWORD: 123456789